image: Visual Studio 2019
skip_branch_with_pr: true

environment:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  BUILD_ARTIFACT_PATH: build-artifacts

install:
  - choco install dotnet-sdk --version 5.0.200

build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: dotnet build --no-restore -c Release
  - ps: dotnet test --no-restore /p:SkipBuildVersioning=true
  - ps: dotnet pack --no-build -c Release /p:PackageOutputPath=$env:BUILD_ARTIFACT_PATH
  
test: false
artifacts:
  - path: '**\$(BUILD_ARTIFACT_PATH)\*'

deploy:
  - provider: NuGet
    artifact: /.*nupkg/
    api_key:
      secure: QNfyCsBxCLb4iGmaRd2ep7yYY3RMJKw54B7p+ZcFDo5pb8KnWM0ULl4ml2u38s/w
    on:
      APPVEYOR_REPO_TAG: true
  
  - provider: NuGet
    server: https://nuget.pkg.github.com/TurnerSoftware/index.json
    artifact: /.*\.nupkg/
    skip_symbols: true
    username: TurnerSoftware
    api_key:
      secure: XnTMWCpraeRGwQ/HGCQIneJDAIIsF7MypVnaShycKC95P3+IA0MF+qXV16c8/5jg
    on:
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    artifact: /.*nupkg/
    draft: true
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'TODO'
    auth_token:
      secure: 8WGv8noklaCJAQEBpcs+VShk/Hql5zbyx0VPhMvzUw0RcG7rAd2KxKIh4gazXlBi
    on:
      APPVEYOR_REPO_TAG: true
