version: 'Build {build}'
image: Visual Studio 2019
skip_branch_with_pr: true

build_script:
  - ps: dotnet build -c Release
  - ps: dotnet test
  - ps: dotnet pack --no-build -c Release /p:PackageOutputPath=build-artifacts
  
test: false
artifacts:
  - path: '.\build-artifacts\*'

deploy:
  - provider: NuGet
    artifact: /.*nupkg/
    api_key:
      secure: QNfyCsBxCLb4iGmaRd2ep7yYY3RMJKw54B7p+ZcFDo5pb8KnWM0ULl4ml2u38s/w
    on:
      APPVEYOR_REPO_TAG: true
  
  - provider: NuGet
    server: https://nuget.pkg.github.com/TurnerSoftware/index.json
    artifact: /.*\.nupkg/
    skip_symbols: true
    username: TurnerSoftware
    api_key:
      secure: XnTMWCpraeRGwQ/HGCQIneJDAIIsF7MypVnaShycKC95P3+IA0MF+qXV16c8/5jg
    on:
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    artifact: /.*nupkg/
    draft: true
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'TODO'
    auth_token:
      secure: 8WGv8noklaCJAQEBpcs+VShk/Hql5zbyx0VPhMvzUw0RcG7rAd2KxKIh4gazXlBi
    on:
      APPVEYOR_REPO_TAG: true
