trigger:
- main

jobs:
- job: BuildApplication
  pool:
    vmImage: ubuntu-latest

  variables:
    BUILD_ARTIFACT_PATH: $(Build.ArtifactStagingDirectory)
 
  steps:
  - task: UseDotNet@2
    displayName: Install .NET 5 SDK
    inputs:
      version: 5.0.x
  - task: UseDotNet@2
    displayName: Install .NET 6 SDK
    inputs:
      version: 6.0.x

  - script: dotnet --info
    displayName: .NET info

  - script: dotnet restore
    displayName: Install dependencies

  - script: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
    displayName: Build

  - script: dotnet test --no-restore /p:SkipBuildVersioning=true
    displayName: Test
       
  - script: dotnet pack --no-build -c Release /p:PackageOutputPath=$(BUILD_ARTIFACT_PATH) /p:ContinuousIntegrationBuild=true
    displayName: Pack
    
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      ArtifactName: BuildVersioning
      pathToPublish: $(BUILD_ARTIFACT_PATH)
