trigger:
- main

jobs:
- job: BuildApplication
  pool:
    vmImage: ubuntu-latest

  variables:
    BUILD_CONFIGURATION: Release
    BUILD_ARTIFACT_PATH: $(Build.ArtifactStagingDirectory)
 
  steps:
  - script: dotnet --version
    displayName: .NET version

  - script: dotnet restore
    displayName: Install dependencies

  - script: dotnet build --no-restore -c $(BUILD_CONFIGURATION)
    displayName: Build

  - script: dotnet test --no-restore /p:SkipBuildVersioning=true
    displayName: Test
       
  - script: dotnet pack --no-build -c $(BUILD_CONFIGURATION) /p:PackageOutputPath=$(BUILD_ARTIFACT_PATH)
    displayName: Pack
    
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      ArtifactName: BuildVersioning
      pathToPublish: $(BUILD_ARTIFACT_PATH)
